#!/bin/bash
TMPFILE=`tempfile`
BINFILE=`tempfile`

# Control, nonnegative offsets.
cat > "${TMPFILE}" <<INPUT
.version 1.4
.target sm_12, map_f64_to_f32
.entry underrun () {
    .shared .u32 s[1];
    red.shared.and.b32 [s+0], 0;
}
INPUT

RET=2
ptxas -arch sm_12 -o "${BINFILE}" "${TMPFILE}" && RET=0

if [ "${RET}" -ne 0 ]; then
    exit "${RET}"
fi

# Actual test
cat > "${TMPFILE}" <<INPUT
.version 1.4
.target sm_12, map_f64_to_f32
.entry underrun () {
    .shared .u32 s[1];
    red.shared.and.b32 [s-4], 0;
}
INPUT

RET=0
ptxas -arch sm_12 -o "${BINFILE}" "${TMPFILE}" 2>/dev/null && RET=1

rm -f "${BINFILE}" "${TMPFILE}"
exit "${RET}"
